config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # Mount the MissionControl::Jobs::Engine at /jobs
  mount MissionControl::Jobs::Engine, at: "/jobs"

  namespace :heroku do
    resources :stacks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  before_create :set_uuid

  has_based_uuid

  def to_param
    based_uuid
  end

  private

  def set_uuid
    return if self.class.attribute_types["id"].type != :uuid

    self.id ||= SecureRandom.uuid_v7
  end
end

app/models/heroku.rb
module Heroku
  def self.table_name_prefix
    "heroku_"
  end
end

app/models/heroku/stack.rb
class Heroku::Stack < ApplicationRecord
  validates :heroku_identifier, presence: true, uniqueness: true
  validates :heroku_name, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true

  validates :heroku_identifier, format: {
    with: /\A[a-f0-9]{8}-([a-f0-9]{4}-){3}[a-f0-9]{12}\z/,
    message: "must be a valid UUID"
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/heroku/stacks_controller.rb
class Heroku::StacksController < ApplicationController
  before_action :set_heroku_stack, only: %i[ show edit update destroy ]

  # GET /heroku/stacks or /heroku/stacks.json
  def index
    @heroku_stacks = Heroku::Stack.all
  end

  # GET /heroku/stacks/1 or /heroku/stacks/1.json
  def show
  end

  # GET /heroku/stacks/new
  def new
    @heroku_stack = Heroku::Stack.new
  end

  # GET /heroku/stacks/1/edit
  def edit
  end

  # POST /heroku/stacks or /heroku/stacks.json
  def create
    @heroku_stack = Heroku::Stack.new(heroku_stack_params)

    respond_to do |format|
      if @heroku_stack.save
        format.html { redirect_to heroku_stack_url(@heroku_stack), notice: "Stack was successfully created." }
        format.json { render :show, status: :created, location: @heroku_stack }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @heroku_stack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heroku/stacks/1 or /heroku/stacks/1.json
  def update
    respond_to do |format|
      if @heroku_stack.update(heroku_stack_params)
        format.html { redirect_to heroku_stack_url(@heroku_stack), notice: "Stack was successfully updated." }
        format.json { render :show, status: :ok, location: @heroku_stack }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @heroku_stack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heroku/stacks/1 or /heroku/stacks/1.json
  def destroy
    @heroku_stack.destroy!

    respond_to do |format|
      format.html { redirect_to heroku_stacks_url, notice: "Stack was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_heroku_stack
      @heroku_stack = Heroku::Stack.find_by_based_uuid(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def heroku_stack_params
      params.require(:heroku_stack).permit(:name, :heroku_identifier, :heroku_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/heroku/stacks_helper.rb
module Heroku::StacksHelper
end

app/views/heroku/stacks/_form.html.erb
<%= form_with(model: heroku_stack, class: "contents") do |form| %>
  <% if heroku_stack.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(heroku_stack.errors.count, "error") %> prohibited this heroku_stack from being saved:</h2>

      <ul>
        <% heroku_stack.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :heroku_identifier %>
    <%= form.text_field :heroku_identifier, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :heroku_name %>
    <%= form.text_field :heroku_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/heroku/stacks/_stack.html.erb
<div id="<%= dom_id stack %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= stack.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Heroku ID:</strong>
    <%= stack.heroku_identifier %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Heroku name:</strong>
    <%= stack.heroku_name %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this stack", stack, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this stack", edit_heroku_stack_path(stack), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/heroku/stacks/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing stack</h1>

  <%= render "form", heroku_stack: @heroku_stack %>

  <%= link_to "Show this stack", @heroku_stack, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to stacks", heroku_stacks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/heroku/stacks/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Stacks</h1>
    <%= link_to "New stack", new_heroku_stack_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="heroku_stacks" class="min-w-full">
    <%= render @heroku_stacks %>
  </div>
</div>

app/views/heroku/stacks/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New stack</h1>

  <%= render "form", heroku_stack: @heroku_stack %>

  <%= link_to "Back to stacks", heroku_stacks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/heroku/stacks/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @heroku_stack %>

    <%= link_to "Edit this stack", edit_heroku_stack_path(@heroku_stack), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this stack", heroku_stack_path(@heroku_stack), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to stacks", heroku_stacks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HerokuApplicationManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Hello World!</h1>